### ISSUE TITLE
Research best protocol to use for the data transfer

### ISSUE THREAD

**Issue by rudy-patel** [rudy-patel/imageAnalysisSystem#20]
We need a way to transfer data back and forth from the raspberry pi to the webserver. Let's research some protocols that could be good for this use case (my guess is HTTP, could be wrong). It may also be worth touching base with whoever is/has worked on the ML model to figure out what needs to be transferred.

**Comment by CaixiangFan** [comment]
I feel websocket might be an alternative if this is an event-driven model. It depends on how you design the communication pattern between the RPi and webserver. Take a look at this [article](https://ably.com/topic/websockets-vs-http#:~:text=Unlike%20HTTP%2C%20where%20you%20have,request%2Fresponse%2Dbased%20methods.) on the difference WebSockets vs HTTP.

**Comment by CaixiangFan** [comment]
Here is another [post](https://www.geeksforgeeks.org/what-is-web-socket-and-how-it-is-different-from-the-http/) which I think is helpful to decide which one (HTTP or WebSocket) to go.
