### ISSUE TITLE
Establish live camera feed connection to web server

### ISSUE THREAD

**Issue by rudy-patel** [rudy-patel/imageAnalysisSystem#21]
**User statement**
*As a user, I would like to see a live camera feed on my dashboard.*

**Proposed solution**
Let's find a way to relay a live camera feed to the web server and display it on the dashboard. It doesn't have to be super up-to-date, some lag should be okay. 

**Development notes**
Add any other notes, context, or screenshots relevant to the ticket here

**Comment by CaixiangFan** [comment]
Here is a [solution](https://towardsdatascience.com/video-streaming-in-web-browsers-with-opencv-flask-93a38846fe00) of Flask + OpenCV for your reference. It uses RTSP to relay the live stream.

**Comment by kaden-dreger** [comment]
This is closed, we having a live camera feed from the pi to the server.
