### ISSUE TITLE
Research ML models for facial recognition

### ISSUE THREAD

**Issue by rudy-patel** [rudy-patel/imageAnalysisSystem#25]
Let's identify a few options that will work with the camera and the raspberry pi we have selected.

**Comment by jpaetsch** [comment]
Followed this resource to set up a locally-working series of Python scripts and file structure to locally detect faces using OpenCV:  https://www.tomshardware.com/how-to/raspberry-pi-facial-recognition
Proved that it can work successfully - future work will involve setting this up on the server side to process incoming client frames.
