### ISSUE TITLE
Run facial recognition model on raspberry pi

### ISSUE THREAD

**Issue by rudy-patel** [rudy-patel/imageAnalysisSystem#27]
**User statement**
*As a user, I would like to run the facial recognition model locally on the raspberry pi.*

**Proposed solution**
Run the chosen ML model on the raspberry pi. The results can just be printed to the command line for this story.

**Development notes**
Add any other notes, context, or screenshots relevant to the ticket here

**Comment by jpaetsch** [comment]
Successfully ran a facial recognition OpenCV model on the Pi locally.  Next steps will involve setting up event notifications to the main web server.
