### ISSUE TITLE
Connect ML Models to Server Events

### ISSUE THREAD

**Issue by jpaetsch** [rudy-patel/imageAnalysisSystem#67]
Set up ML model output so that it can be bundled into an event that is reported/recorded by the server.  This issue heavily overlaps with tasks in the communication project board.

**Comment by jpaetsch** [comment]
Successfully set up the framework for frame processing and streaming to the web browser.  Additionally have an API endpoint that can successfully add new events to the database.  Need to combine this functionality to send facial recognition events (and figure out the best framework so future events can be easily added)

**Comment by rudy-patel** [comment]
Done.
